import { TermsPage, Section, styles } from "@/components/TermsPage";

export const metadata = { title: "Terms of Service — Plain English, Please" };

export default function PlainEnglishTerms() {
  return (
    <TermsPage appName="Plain English, Please" lastUpdated="16 May 2026">
      <Section title="1. Acceptance of Terms">
        <p>By downloading or using Plain English, Please, you agree to these Terms of Service. If you do not agree, do not use the app. These terms form a binding agreement between you and Knoodlepot Studio, a UK sole trader.</p>
      </Section>

      <Section title="2. The Service">
        <p>Plain English, Please is an Android app that passes passive-aggressive, corporate, or diplomatically difficult remarks through Claude AI, returning a translation of what was actually meant, a polished response, and an internal monologue. The Twat-O-Meter rates the offender on a scale of one to five teacups. Translations can be saved to history or shared as an image.</p>
        <p>All content is provided for entertainment and humour purposes only. Translations and responses generated by the app are produced by AI and should not be relied upon for legal, professional, or interpersonal decisions.</p>
      </Section>

      <Section title="3. Accounts">
        <p>You must create an account to use Plain English, Please. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. You must be aged 13 or over to create an account.</p>
      </Section>

      <Section title="4. Subscriptions and Payments">
        <p>Plain English, Please may offer a free tier and optional paid subscription. Any purchases are processed through Google Play in accordance with Google&apos;s payment terms. Subscription management, cancellation, and refunds are handled by Google Play. We do not process payments directly.</p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>You agree not to:</p>
        <ul style={styles.list}>
          <li>Use the app for any unlawful purpose.</li>
          <li>Submit content that is designed to harass, defame, or threaten any individual.</li>
          <li>Attempt to reverse-engineer, decompile, or tamper with the app.</li>
          <li>Use automated tools to access the service beyond normal app usage.</li>
          <li>Share generated content in a way that misrepresents it as factual or professional advice.</li>
        </ul>
      </Section>

      <Section title="6. Intellectual Property">
        <p>All app content, design, and code are the property of Knoodlepot Studio or its licensors. You may save and share individual translation results for personal, non-commercial use. You may not reproduce, distribute, or exploit app content commercially without written permission.</p>
      </Section>

      <Section title="7. Disclaimer of Warranties">
        <p>Plain English, Please is provided &quot;as is&quot; without warranties of any kind. AI-generated content is produced for entertainment purposes and may not accurately reflect the intent of the original remark. We do not guarantee that the service will be uninterrupted or error-free. Use of the app is at your own risk.</p>
      </Section>

      <Section title="8. Limitation of Liability">
        <p>To the fullest extent permitted by UK law, Knoodlepot Studio shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app or reliance on any generated content. Our total liability to you shall not exceed the amount you paid for the service in the three months preceding the claim.</p>
      </Section>

      <Section title="9. Governing Law">
        <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
      </Section>

      <Section title="10. Changes to These Terms">
        <p>We may update these terms from time to time. Continued use of the app after changes are posted constitutes acceptance of the updated terms.</p>
      </Section>

      <Section title="11. Contact">
        <p>For any questions about these terms: <a href="mailto:knoodlepot@knoodlepotstudio.com" style={styles.link}>knoodlepot@knoodlepotstudio.com</a></p>
      </Section>
    </TermsPage>
  );
}
