import { TermsPage, Section, styles } from "@/components/TermsPage";

export const metadata = { title: "Terms of Service — Veracitor" };

export default function VeracitorTerms() {
  return (
    <TermsPage appName="Veracitor" lastUpdated="16 May 2026">
      <Section title="1. Acceptance of Terms">
        <p>By downloading or using Veracitor, you agree to these Terms of Service. If you do not agree, do not use the app. These terms form a binding agreement between you and Knoodlepot Studio, a UK sole trader.</p>
      </Section>

      <Section title="2. The Service">
        <p>Veracitor is a fact-checking app for Android. It passes claims through Claude AI, which breaks them down component by component, identifies sub-claims, checks each independently, and returns a verdict of TRUE, PARTLY TRUE, FALSE, or MISLEADING with a source-backed breakdown. The app is country-aware and uses your location to apply relevant context.</p>
        <p>Veracitor is provided for informational purposes. Verdicts are generated by AI and reflect the best available information at the time of the check. They do not constitute legal, professional, or journalistic advice. We do not guarantee the accuracy of any verdict.</p>
      </Section>

      <Section title="3. Accounts">
        <p>You must create an account to use Veracitor. You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. You must be aged 13 or over to create an account.</p>
      </Section>

      <Section title="4. Subscriptions and Payments">
        <p>Veracitor offers a free tier and optional paid subscription. The free tier provides five fact-checks per day. Subscriptions are billed through Google Play in accordance with Google&apos;s payment terms. Subscription management, cancellation, and refunds are handled by Google Play. We do not process payments directly.</p>
      </Section>

      <Section title="5. Acceptable Use">
        <p>You agree not to:</p>
        <ul style={styles.list}>
          <li>Use the app for any unlawful purpose.</li>
          <li>Submit content that is defamatory, threatening, or designed to harass an individual.</li>
          <li>Attempt to reverse-engineer, decompile, or tamper with the app.</li>
          <li>Use automated tools to submit claims beyond normal app usage.</li>
        </ul>
      </Section>

      <Section title="6. Intellectual Property">
        <p>All app content, design, and code are the property of Knoodlepot Studio or its licensors. Verdicts generated by the app are produced for your personal use. You may share individual verdicts for non-commercial purposes. You may not reproduce or exploit app content commercially without written permission.</p>
      </Section>

      <Section title="7. Disclaimer of Warranties">
        <p>Veracitor is provided &quot;as is&quot; without warranties of any kind. AI-generated verdicts are not infallible. We do not guarantee that the service will be uninterrupted, error-free, or that verdicts will be accurate in all cases. Use of the app is at your own risk.</p>
      </Section>

      <Section title="8. Limitation of Liability">
        <p>To the fullest extent permitted by UK law, Knoodlepot Studio shall not be liable for any indirect, incidental, or consequential damages arising from your use of the app or reliance on any verdict. Our total liability to you shall not exceed the amount you paid for the service in the three months preceding the claim.</p>
      </Section>

      <Section title="9. Governing Law">
        <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
      </Section>

      <Section title="10. Changes to These Terms">
        <p>We may update these terms from time to time. Continued use of the app after changes are posted constitutes acceptance of the updated terms.</p>
      </Section>

      <Section title="11. Contact">
        <p>For any questions about these terms: <a href="mailto:knoodlepot@knoodlepotstudio.com" style={styles.link}>knoodlepot@knoodlepotstudio.com</a></p>
      </Section>
    </TermsPage>
  );
}
